### ISSUE TITLE
Run formatters in nodejs runner

### ISSUE THREAD

**Issue by macbre** [macbre/phantomas#186]
Instead of running results formatter in PhantomJS scope, run them on JSON results returned by PhantomJS "inner" script.

Needed for #10 and #12 

`--format` is now an alias of `--reporter` (`-R` shortcut)
### Subtasks
- [x] move formatters "framework" to nodejs runner script
- [x] migrate JSON reporter
- [x] migrate TAP reporter
- [x] migrate CSV reporter (using [csv-string](https://npmjs.org/package/csv-string))
- [x] migrate plain reporter
