### ISSUE TITLE
CLI options are camel cased, then do not work

### ISSUE THREAD

**Issue by gmetais** [macbre/phantomas#863]
When using the CLI with a multiple words option, such as `--user-agent` `--auth-user` `--wait-for-selector`, they get ignored.

The reason is [commander](https://www.npmjs.com/package/commander), the package that handles the CLI options. It transforms multiple words into camel case.

But in Phantomas' code, the options are expected to have dashes. Example: [here](https://github.com/macbre/phantomas/blob/23168f5ec3f5e8450c0d037059bddaac4ed16e63/extensions/waitForSelector/waitForSelector.js#L8).

**Comment by macbre** [comment]
So we now have two uses cases - `phantomas` as npm module and used as a CLI tool. Both of these expose `dashed-options` for the user, but with the CLI they get `camelCased`. I'd try to to [de-camelify](https://github.com/sindresorhus/decamelize) them in CLI or normalise them inside `getParam()` function.

This will keep the behaviour consistent and avoid introducing a breaking change for a ton of options (see below).

* [x] normalise options (camel-cased by commander) to `dashed-notation` using [de-camelify](https://github.com/sindresorhus/decamelize)
* [ ] add CLI test cases to CI pipeline

## TODO list

```
~/src/git/phantomas$ ack 'getParam' | egrep '[a-z]-' | awk '{print "* [ ] `" $0 "`"} '
```

* [ ] `extensions/waitForSelector/waitForSelector.js:8:  var selector = phantomas.getParam("wait-for-selector");`
* [ ] `extensions/userAgent/userAgent.js:17:    phantomas.getParam("phone-landscape") === true`
* [ ] `extensions/userAgent/userAgent.js:25:    phantomas.getParam("tablet-landscape") === true`
* [ ] `extensions/userAgent/userAgent.js:32:  const param = phantomas.getParam("user-agent");`
* [ ] `extensions/postLoadDelay/postLoadDelay.js:8:  var delay = parseInt(phantomas.getParam("post-load-delay"), 10);`
* [ ] `extensions/httpAuth/httpAuth.js:7:  var username = phantomas.getParam("auth-user") || "",`
* [ ] `extensions/httpAuth/httpAuth.js:8:    password = phantomas.getParam("auth-pass") || "";`
* [ ] `extensions/waitForEvent/waitForEvent.js:8:  var eventName = phantomas.getParam("wait-for-event");`
* [ ] `extensions/pageSource/pageSource.js:12:  if (!phantomas.getParam("page-source")) {`
* [ ] `extensions/pageSource/pageSource.js:24:      .getParam("page-source-dir", workingDirectory)`
* [ ] `extensions/filmStrip/filmStrip.js:19:  if (!phantomas.getParam("film-strip")) {`
* [ ] `extensions/filmStrip/filmStrip.js:27:      .getParam("film-strip-dir", "filmstrip", "string")`
* [ ] `extensions/filmStrip/filmStrip.js:30:      .getParam("film-strip-prefix", "screenshot", "string")`
* [ ] `extensions/filmStrip/filmStrip.js:33:  var zoomFactor = phantomas.getParam("film-strip-zoom-factor", 0.5);`
* [ ] `extensions/filmStrip/filmStrip.js:98:  if (phantomas.getParam("film-strip", false, "string")) {`
* [ ] `extensions/filmStrip/filmStrip.js:100:    var timePoints = phantomas.getParam("film-strip").split(",");`
* [ ] `modules/analyzeCss/analyzeCss.js:45:  if (phantomas.getParam("analyze-css") !== true) {`
* [ ] `modules/analyzeCss/analyzeCss.js:78:		if (phantomas.getParam('auth-user') && phantomas.getParam('auth-pass')) {`
* [ ] `modules/analyzeCss/analyzeCss.js:79:			options.push('--auth-user', phantomas.getParam('auth-user'));`
* [ ] `modules/analyzeCss/analyzeCss.js:80:			options.push('--auth-pass', phantomas.getParam('auth-pass'));`
* [ ] `modules/javaScriptBottlenecks/scope.js:3:  var spyEval = (await phantomas.getParam("spy-eval")) === true;`
* [ ] `modules/blockDomains/blockDomains.js:11:    noExternalsMode = phantomas.getParam("no-externals") === true,`
* [ ] `modules/blockDomains/blockDomains.js:13:    allowedDomains = phantomas.getParam("allow-domain"),`
* [ ] `modules/blockDomains/blockDomains.js:16:    blockedDomains = phantomas.getParam("block-domain"),`

**Comment by macbre** [comment]
```
$ DEBUG=* ./bin/phantomas.js  --user-agent="foo/bar" --wait-for-selector="#app.loaded" 
  phantomas:cli argv: ["/home/macbre/.nvm/versions/node/v12.18.2/bin/node","/home/macbre/src/git/phantomas/bin/phantomas.js","--user-agent=foo/bar","--wait-for-selector=#app.loaded"] +0ms
  phantomas:cli opts: {"viewport":"800x600","externals":true,"timeout":15,"userAgent":"foo/bar","waitForSelector":"#app.loaded"} +1ms
```

**Comment by macbre** [comment]
@gmetais - will be fixed by #904
